<?php //
// echo $cart->getProductID();
// echo $cart->getQTY();
// echo $cart->getPrice(); 
// echo Mage::getBaseUrl("skin/image/media/product/") 
// echo $cart->getname();
// echo $cart->getprice();         ?>





<div class="view1">
    <div class="view2">
        <input type="hidden" name="Product_id" value="">
        <img src="" alt="image not found">
        <p>Product Name:
            <?php ?>
        </p>

        <p name='price'>Price:

            <?php ?>
        </p>
        <label for="quantity">Quantity:</label>
        <input type="number" id="quantity" name="qty" min="" value="1">
        <button type="submit" id="addToCartBtn">Remove</button>
        <button type="submit" id="addToCartBtn">Place Order</button>
    </div>

</div>