<div class="form">
    <div class="class1">
        <form action="" method="post">
            <input type="hidden" name="category[category_id]">

            <label for="">New Password</label>
            <input type="text" name="">
            <label for="">Re-type Password</label>
            <input type="text" name="">
            <input type="submit" value="Submit">
        </form>
    </div>
</div>