<?php $customerModel = $this->getCustomerForm() ?>

<title>Registration Form</title>

<body>
    <div class="container">
        <h2>Registration Form</h2>
        <form id="registrationForm" action="<?php echo Mage::getBaseUrl('customer/account/save') ?>" method="post">
            <input type="hidden" id="customer_id" name="customer[customer_id]" value="<?php echo $customerModel->getcustomer_id(); ?>">

            <label for="first_name">First Name:</label>
            <input type="text" id="first_name" name="customer[first_name]" value="<?php echo $customerModel->getfirst_name(); ?>"required>

            <label for="last_name">Last Name:</label>
            <input type="text" id="last_name" name="customer[last_name]" value="<?php echo $customerModel->getlast_name(); ?>" required>

            <label for="customer_email">Email:</label>
            <input type="email" id="customer_email" name="customer[customer_email]" required>

            <label for="billing_address">Billing Address:</label>
            <input type="text" id="billing_address" name="customer[billing_address]" required>

            <label for="billing_city">Billing City:</label>
            <input type="text" id="billing_city" name="customer[billing_city]" required>

            <label for="billing_region">Billing Region:</label>
            <input type="text" id="billing_region" name="customer[billing_region]" required>

            <label for="billing_country">Billing Country:</label>
            <input type="text" id="billing_country" name="customer[billing_country]" required>

            <label for="billing_phone">Billing Phone:</label>
            <input type="tel" id="billing_phone" name="customer[billing_phone]" required>

            <label for="shipping_address">Shipping Address:</label>
            <input type="text" id="shipping_address" name="customer[shipping_address]" required>

            <label for="shipping_city">Shipping City:</label>
            <input type="text" id="shipping_city" name="customer[shipping_city]" required>

            <label for="shipping_region">Shipping Region:</label>
            <input type="text" id="shipping_region" name="customer[shipping_region]" required>

            <label for="shipping_country">Shipping Country:</label>
            <input type="text" id="shipping_country" name="customer[shipping_country]" required>

            <label for="shipping_phone">Shipping Phone:</label>
            <input type="tel" id="shipping_phone" name="customer[shipping_phone]" required>

            <label for="password">Password:</label>
            <input type="text" id="password" name="customer[password]" required>

            <label for="default">Default:</label>
            <input type="checkbox" id="default" name="customer[default]">

            <input type="submit" value="Submit">
        </form>
    </div>



</body>