

</head>

<body>

    <h2>Customer Details</h2>

    <table id="customerTable">
        <thead>
            <tr>
                <th>Customer ID</th>
                <th>Customer Email</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Billing Address</th>
                <th>Billing City</th>
                <th>Billing Region</th>
                <th>Billing Country</th>
                <th>Billing Phone</th>
                <th>Shipping City</th>
                <th>Shipping Region</th>
                <th>Shipping Country</th>
                <th>Shipping Phone</th>
                <th>Default</th>
                <th>Delete</th>
                <th>Update</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($customerCollection->getData() as $customer): ?>
                <tr>
                    <td>
                        <?php echo $customer->getcustomer_id(); ?>
                    </td>
                    <td>
                        <?php echo $customer->getcustomer_email(); ?>
                    </td>
                    <td>
                        <?php echo $customer->getfirst_name(); ?>
                    </td>
                    <td>
                        <button class="edit-button"
                            onclick="window.location.href='form?id=<?php echo $customer->getId(); ?>'">Edit</button>
                    </td>
                    <td>
                        <button class="delete-button"
                            onclick="window.location.href='delete?id=<?php echo $customer->getId(); ?>'">Delete</button>
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <script>
        
        const table = document.getElementById('customerTable');

        customers.forEach(customer => {
            const row = table.insertRow();
            Object.values(customer).forEach(value => {
                const cell = row.insertCell();
                cell.textContent = value;
            });
        });
    </script>

</body>

</html>