<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Form</title>
</head>
<style>
    .form {
        display: flex;
        /* text-align: center; */
        justify-content: center;
    }
</style>

<body>
    <div class="form">
        <form action="<?php echo $this->getUrl('Catalog/Product/save')?>" method="post">
            <h2>Product Form</h2>
            <label for="name">Name:</label><br>
            <input type="text" id="name" name="name"><br>

            <label for="sku">SKU:</label><br>
            <input type="text" id="sku" name="sku"><br>


            <label for="color">Color:</label><br>
            <input type="text" id="color" name="color"><br>

            <label for="size">Size:</label><br>
            <input type="text" id="size" name="size"><br>

            <label for="description">Description:</label><br>
            <textarea id="description" name="description"></textarea><br>

            <label for="image_link">Image Link:</label><br>
            <input type="text" id="image_link" name="image_link"><br>

            <label for="link">Link:</label><br>
            <input type="text" id="link" name="link"><br>

            <label for="category_id">Category ID:</label><br>
            <input type="text" id="category_id" name="category_id"><br>

            <label for="price">Price:</label><br>
            <input type="text" id="price" name="price"><br>

            <label for="mfr_cost">Manufacturer Cost:</label><br>
            <input type="text" id="mfr_cost" name="mfr_cost"><br>

            <label for="shipping_cost">Shipping Cost:</label><br>
            <input type="text" id="shipping_cost" name="shipping_cost"><br>

            <label for="total_cost">Total Cost:</label><br>
            <input type="text" id="total_cost" name="total_cost"><br>

            <label for="margin_percentage">Margin Percentage:</label><br>
            <input type="text" id="margin_percentage" name="margin_percentage"><br>

            <label for="min_price">Minimum Price:</label><br>
            <input type="text" id="min_price" name="min_price"><br>

            <label for="status">Status:</label><br>
            <input type="radio" id="status" name="status">Active
            <input type="radio" id="status" name="status">Disactive<br>

            <input type="submit" value="Submit">
        </form>
    </div>
</body>

</html>