<?php $category_model = $this->getCategory() ?>



<div class="form">
    <div class="class1">
        <form action="<?php echo Mage::getBaseUrl('admin/catalog_category/save') ?>" method="post">
            <input type="hidden" name="category[category_id]" value="<?php echo $category_model->getcategory_id() ?>">

            <label for="">Category_Name</label>
            <input type="text" name="category[category_name]" value="<?php echo $category_model->getcategory_name() ?>">
            <label for="">Status</label>
            <select id="status" name="category[status]">
                <option value="0">Active</option>
                <option value="1">Disactive</option>
            </select>
            <input type="submit" value="Submit">
        </form>
    </div>
</div>