<?php
$categoryCollection = Mage::getModel('Catalog/Category')->getCollection();
// print_r($categoryCollection->getData());
// foreach ($productCollection->getData() as $product) {
//     var_dump($product->getProductId());
//     // print_r($product);
// }
?>






<div class="container">
    <h2>Product List</h2>
    <table id="productTable" class="display">
        <thead>
            <tr>
                <th>ID</th>
                <th>Category_Name</th>
                <th>Status</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($categoryCollection->getData() as $category): ?>
                <tr>
                    <td>
                        <?php echo $category->getcategoryId(); ?>
                    </td>
                    <td>
                        <?php echo $category->getcategoryname(); ?>
                    </td>
                    <td>
                        <?php echo $category->getStatus(); ?>
                    </td>
                    <td>
                        <button class="edit-button"
                            onclick="window.location.href='form?id=<?php echo $category->getId(); ?>'">Edit</button>
                    </td>
                    <td>
                        <button class="delete-button"
                            onclick="window.location.href='delete?id=<?php echo $category->getId(); ?>'">Delete</button>
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>


<!-- DataTables JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function () {
        $('#productTable').DataTable({
            // You can add options for DataTables here
            // Example:
            // "paging": true,
            // "ordering": true,
            // "info": true,
            // "searching": true
        });
    });
</script>