<h1>calculator</h1>

<form action="<?php echo Mage::getBaseUrl("Bmicalculator/calculator/save") ?>">
    <input type="text" name="calculator[user_name]" id="" value="<?php echo $this->sessionName(); ?>">user name
    <input type="hidden" name="calculator[session_id]" value="<?php echo $this->sessionId(); ?>">
    <br>
    <br>
    <select id="" name="calculator[weight_unit]">
        <option value="kilogram">kilogram</option>
        <option value="pounds">pounds</option>
    </select>
    <input type="number" name="calculator[weight]">Weight
    <br>
    <br>
    <select id="" name="calculator[height_unit]">
        <option value="meter">meter</option>
        <option value="feet">feet</option>
    </select>
    <input type="number" name="calculator[height]">height
    <br>
    <br>
    <input type="submit">
</form>