<?php
$productId = $this->getRequest()->getParams('id');
if ($productId) {
    $productData = Mage::getModel('catalog/product')->getCollection()->addFieldToFilter('product_id', $productId);
} else {
    $productData = Mage::getModel('catalog/product')->getCollection();
}
?>

<?php foreach ($productData->getData() as $product): ?>
    <form action="<?php echo Mage::getBaseUrl('sales/quote/add') ?>" method="post">
        <div class="view1">
            <div class="view2">
                <input type="hidden" name="Product_id" value="<?php echo $product->getProductId() ?>">
                <img src="<?php echo Mage::getBaseUrl("skin/image/media/product/") . $product->getImageLink() ?>"
                    alt="image not found">
                <p>Product Name:
                    <?php echo $product->getname(); ?>
                </p>

                <p name='price'>Price:

                    <?php echo $product->getprice(); ?>
                </p>
                <label for="quantity">Quantity:</label>
                <input type="number" id="quantity" name="qty" min="" value="1">
                <button type="submit" id="addToCartBtn">Add to Cart</button>
            </div>

        </div>
    </form>
<?php endforeach; ?>