<?php
$productId = $this->getRequest()->getParams('id');
if ($productId) {
    $productData = Mage::getModel('catalog/product')->getCollection()->addFieldToFilter('product_id', $productId);
} else {
    $productData = Mage::getModel('catalog/product')->getCollection();
}
?>

<?php foreach ($productData->getData() as $product): ?>
    <form action="<?php echo Mage::getBaseUrl('sales/quote/add') ?>" method="post">
        <div class="view1">
            <div class="view2">
                <input type="hidden" name="Product_id" value="<?php echo $product->getProductId() ?>">
                <div>

                    <img src="<?php echo Mage::getBaseUrl("skin/image/media/product/") . $product->getImageLink() ?>"
                        alt="image not found">
                </div>
                <div class="image">

                    <p>Product Name:
                        <?php echo $product->getname(); ?>
                    </p>

                    <p name='price'>Price:

                        <?php echo $product->getprice(); ?>
                    </p>
                    <p name='description'>Description:
                        <br>
                        <?php echo $product->getdescription(); ?>
                    </p>
                    <!-- <label for="quantity">Quantity:</label> -->
                    <p><span style="font-size: 14px">Quantity</span></p>
                    <div class="quantity-box">
                        <div class="quantity-btn" onclick="decrease()">-</div>
                        <div><input type="number" name="qty" min="1" max="10" value="1" id="quantity"></div>
                        <div class="quantity-btn" onclick="increase()">+</div>
                    </div>
                    <!-- <input type="number" id="quantity" name="qty" min="" value="1"> -->
                    <button type="submit" id="addToCartBtn">Add to Cart</button>
                </div>
            </div>

        </div>
    </form>
<?php endforeach; ?>
<script>
    let qnt = document.getElementById('quantity');
    function increase() {
        if (parseInt(qnt.value) + 1 <= 5)
            qnt.value = parseInt(qnt.value) + 1;
    }
    function decrease() {
        if (parseInt(qnt.value) - 1 >= parseInt(qnt.getAttribute('min')))
            qnt.value = parseInt(qnt.value) - 1;
    }
</script>