<?php $product = $this->getData(); ?>

<form action="<?php echo Mage::getBaseUrl('sales/quote/add') ?>" method="post">
    <div class="view1">
        <div class="view2">
            <input type="hidden" name="cart[Product_id]" value="<?php echo $product->getProduct_id() ?>">
            <img src="<?php echo Mage::getBaseUrl("skin/image/media/product/") . $product->getImageLink() ?>"
                alt="image not found">
            <p>Product Name:
                <?php echo $product->getname(); ?>
            </p>
            <label for="quantity">Quantity:</label>
            <input type="number" id="quantity" name="cart[qty]" min="" value="1">
            <button type="submit" id="addToCartBtn">Add to Cart</button>
        </div>

    </div>
</form>