<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>From</title>
</head>
<body>
    <div><?php echo $this->getChild('head') ->toHtml();?>
</div>
    <div>
    <?php echo $this->getChild('header') ->toHtml();?>
    </div>
    <div>
    <?php echo $this->getChild('footer') ->toHtml();?>
    </div>
    <div>
    <?php echo $this->getChild('left') ->toHtml();?>
    </div>
</body>
</html>