<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>From</title>
    
</head>
<body>
    <div><?php echo $this->getChildHtml('head') ?></div>
    <div><?php echo $this->getChildHtml('header') ?></div>
    <div><?php echo $this->getChildHtml('footer') ?></div>
    <div><?php echo $this->getChildHtml('content') ?></div>
    
</body>
</html>