<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>From</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <?php echo $this->getChildHtml('head') ?>
</head>

<body style="padding: 0;margin: 0;">
    <div>
        <?php echo $this->getChildHtml('header') ?>
    </div>
    <div>
        <?php echo $this->getChildHtml('content') ?>
    </div>
    <div>
        <?php echo $this->getChildHtml('footer') ?>
    </div>
</body>

</html>